### ISSUE TITLE
checklist for STAR to generate Leafcutter result

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#241]
The example STAR command provided by the leafcutter is shown as follows. 

IN THEORY, they should be the same, as the specified parameter are identical.

STAR 
- [x] --genomeDir hg19index/  (Input )
- [x] --twopassMode Basic  (default in py script)
- [x] --outSAMstrandField intronMotif (default parameter value)
- [x] --readFilesCommand zcat (default in py script)  \
- [x] --outSAMtype BAM Unsorted (default in py script)

However, there are two cautions:
1. In leafcutter example, no fastq reads were input in the star program
2. Other parameters not specified in the above command but specified in run_STAR.py may/may not have an impact on the analysis.

That said, it should be safe to proceed with what we have before proven otherwise.

**Comment by Rhopala** [comment]
get√

**Comment by gaow** [comment]
> That said, it should be safe to proceed with what we have before proven otherwise.

@hsun3163 agreed!
