### ISSUE TITLE
Figure checklist for Fine-mapping and integrative analysis

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#335]
MASH

- [x] Figure 6 of mash paper: Pairwise sharing by magnitude of eQTLs among celltypes -- Fix the scale of the heatmap color
- [x] Keep the Increase of effective sample size via effect sharing plot but add another scatter plot to show the number of sample size increasement versus the median cell count from donors; label with text (or color, whichever easier) if time permits.
- [x] Generate the prior heatmap using `plot_U` [in this pipeline](https://github.com/cumc/xqtl-pipeline/blob/main/code/multivariate/MASH/mixture_prior.ipynb) 
- [x] If you run the mixture prior from the start, please use the ED Bovy pipeline, then send that output to Gao.

CAFEH

- Genes best to show: CR1, ABCA7 -- check that slide for COLOC in pseudo-bulk analysis; or whatever 3 genes is fine.
- [ ] Make a summary for the genes you analyzed: how many genes analyzed? how many genes has 1 CS? 2 CS , >= CS? -- > 3rd panel of the figures where they show "CS"

SUSIE:

- [ ] Make a summary of discovery: how many genes ananlyzed? how many genes has 1 CS? 2 CS, 3 CS, >=10 CS
- [ ] For the 3 genes you picked for CAFEH let's make their SuSiE plot for the CS. Show that in parallel with CAFEH result.

For Gao: I'd like to show if possible mvSuSiE results for a couple of genes; also CAFEH for including AD GWAS.

- Prior for mash -- see the last item in MASH section
- Select genes and the CAFEH input for those genes: 3 genes is enough. CR1 (single tissue sig) and something with more tissues .
- Take formatted data from Gao with AD GWAS and run CAFEH on the 2 genes.
